server:
  port: 8080
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://eureka-server:2000/eureka/
spring:
  application:
    name: zuulGeteWay
management:
  endpoints:
    web:
      exposure:
        include: '*'
zuul:
  ignored-services:
    - zuulgeteway
    - monitorserver