
server:
  port: 3000
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:2000/eureka/
spring:
  application:
    name: monitorServer
management:
  endpoints:
    web:
      exposure:
        include: '*'